### ISSUE TITLE
Boost errors on Arch GNU/Linux

### ISSUE THREAD

**Issue by vanyasem** [ubports/qtubuntu#6]
When trying to launch any application:
```
Loading module: 'libubuntu_application_api_desktop_mirclient.so.3.0.0'
[QPA] QMirClientClientIntegration: connection to Mir server failed.

Mir returned: "Failed to connect: not accepted by server"
[2018-09-19 23:54:12.712400] <ERROR> MirConnectionAPI: Caught exception at client library boundary (in mir_connection_release): /build/mir-git/src/mir/src/client/rpc/stream_socket_transport.cpp(168): Throw in function virtual void mir::client::rpc::StreamSocketTransport::send_message(const std::vector<unsigned char>&, const std::vector<mir::Fd>&)
Dynamic exception type: boost::exception_detail::clone_impl<boost::exception_detail::error_info_injector<mir::socket_disconnected_error> >
std::exception::what: Failed to send message to server: Broken pipe
[boost::errinfo_errno_*] = 32, "Broken pipe"
```

Newer ubuntu is also affected:

> Simon Quigley, [19.09.18 23:54]
> [In reply to Ivan Semkin]
> It was removed in Cosmic because of that.
> 
> Simon Quigley, [19.09.18 23:55]
> Ubuntu bumped way before Debian did either way.
> 
> Simon Quigley, [19.09.18 23:55]
> If you're on Arch that's probably expected.

**Comment by peat-psuwit** [comment]
Hello,

Thank you for contributing to UBports. As part of project renaming and the effort to port Ubuntu Touch stack to Ubuntu 20.04, we're incrementally migrating repositories to GitLab.

Your issue is now migrated to:
https://gitlab.com/ubports/core/qtubuntu/-/issues/6

Sorry for your inconvenience.
